name: Tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project/requirements.txt

      - name: Run tests.sh
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh